---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
    - name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 300m
          memory: 300m
        requests:
          cpu: 100m
          memory: 100m
         

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetport: 8080
